---
title: "Test the rejection sampler"
author: "Yihao Gu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source('helper.R')
source('rejection_sampler_negative.R')
library('truncdist')
```

We first visually compare the empirical distribution with the target density.
```{r}
# Rejection sampling
beta = 0.1
alpha = -0.99
Nsim = 10^4
res = rejection_sampler_negative(beta, alpha, Nsim)
sample = res$sample
acceptance_rate = res$ar

# Acceptance rate
cat('The acceptance rate is', acceptance_rate, '.\n')

# Plot
plot_lscale_sample(sample, beta, alpha)
```

Now we fix $\alpha$ and see how the acceptance rate changes as $\beta$ changes.
```{r}
alpha = -0.1
m1 = (1 - sqrt(1 - alpha^2)) / 2
m2 = (1 + sqrt(1 - alpha^2)) / 2

# Case 1: 0 < beta <= m1
breakpoints1 = seq(0.01*m1, m1, length.out=100)
breakpoints1 = matrix(breakpoints1, nrow = 1)
ar1 = apply(breakpoints1, 2, fixed_alpha_ar(alpha))
plot(breakpoints1, ar1, type = 'l', ylim = c(0,1), 
     ylab = 'Acceptance Rate', xlab = expression(beta))
mtext(expression(paste(alpha, " = - 0.1")), side = 3)

# Case 2: m1 < beta < m2
breakpoints2 = seq(m1, m2, length.out=100)
breakpoints2 = matrix(breakpoints2, nrow = 1)
ar2 = apply(breakpoints2, 2, fixed_alpha_ar(alpha))
plot(breakpoints2, ar2, type = 'l', ylim = c(0,1), 
     ylab = 'Acceptance Rate', xlab = expression(beta))
mtext(expression(paste(alpha, " = - 0.1")), side = 3)

# Case 3: beta > m2
breakpoints3 = seq(m2, 10, length.out=100)
breakpoints3 = matrix(breakpoints3, nrow = 1)
ar3 = apply(breakpoints3, 2, fixed_alpha_ar(alpha))
plot(breakpoints3, ar3, type = 'l', ylim = c(0,1), 
     ylab = 'Acceptance Rate', xlab = expression(beta))
mtext(expression(paste(alpha, " = - 0.1")), side = 3)

# Draw the three plots together to see the trend of the acceptance rate.
breakpoints = cbind(breakpoints1, breakpoints2, breakpoints3)
ar = cbind(ar1, ar2, ar3)
plot(breakpoints, ar, type = 'l', ylim = c(0,1), 
     ylab = 'Acceptance Rate', xlab = expression(beta))
mtext(expression(paste(alpha, " = - 0.1")), side = 3)
```




