---
title: "Test"
author: "Yihao Gu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source('rejection_sampler_transformed.R')
source('helper.R')
library('ggplot2')
library('dplyr')
library('purrr')
```

```{r}
# Rejection sampling
a = 0.4268421
c = 8.631319
Nsim = 1e5
q = 0.5
k1 = 16
k2 = 5
start_time <- proc.time()
res = rejection_sampler_transformed(a, c, Nsim, q, k1, k2)
end_time <- proc.time()
print(end_time - start_time)
sample = res$sample
acceptance_rate = res$ar

# Acceptance rate
cat('The acceptance rate is', acceptance_rate, '.\n')

# Plot
plot_lscale_sample(sample, a, c)
```

```{r}
# a small, c positive
# Check acceptance rate via simulation
aseq <- seq(1e-2, 1, length.out = 20)
c = seq(0, 10, length.out = 20)

q = 0.5
k1 = 16
k2 = 5

# Create a dataframe
df <- map_df(aseq, ~{
  c_values  = c / (.x)
  data.frame(
    a = .x,
    c = c,
    acceptance_rate = sapply(c_values, get_acceptance_rate, a = .x, q = q, k1 = k1, k2 = k2)
  )
})

# Plot
p1 = ggplot(df, aes(x=c, y=acceptance_rate, color=a, group=a)) + 
    geom_line() +
    labs(x="a * c", y="Acceptance rate", color="a value", title = "0 < a < 1, c >= 0", ) +
    theme_minimal() +
    scale_y_continuous(limits = c(0, 1)) +
    scale_color_gradient(low="#72EDF2", high="#736EFE")+
    theme(plot.title = element_text(hjust = 0.5))
```

```{r}
# a large, c positive
# Check acceptance rate via simulation
aseq <- seq(1, 100, length.out = 20)
c = seq(0, 10, length.out = 20)

q = 0.5
k1 = 16
k2 = 5

# Create a dataframe
df2 <- map_df(aseq, ~{
  c_values  = c * (.x)
  data.frame(
    a = .x,
    c = c,
    acceptance_rate = sapply(c_values, get_acceptance_rate, a = .x, q = q, k1 = k1, k2 = k2)
  )
})

# Plot
p2 = ggplot(df2, aes(x=c, y=acceptance_rate, color=a, group=a)) + 
    geom_line() +
    labs(x="c / a", y="Acceptance rate", color="a value", title = "a >= 1, c >= 0") +
    theme_minimal() +
    scale_y_continuous(limits = c(0, 1)) +
    scale_color_gradient(low="#72EDF2", high="#736EFE") +
    theme(plot.title = element_text(hjust = 0.5))
```

```{r}
# a large, c negative
# Check acceptance rate via simulation
aseq <- seq(1, 10, length.out = 20)
c = seq(0, 100, length.out = 20)

q = 0.5
k1 = 16
k2 = 5

# Create a dataframe
df3 <- map_df(aseq, ~{
  c_values  = - c * (.x)
  data.frame(
    a = .x,
    c = c,
    acceptance_rate = sapply(c_values, get_acceptance_rate, a = .x, q = q, k1 = k1, k2 = k2)
  )
})

# Plot
p3 = ggplot(df3, aes(x=c, y=acceptance_rate, color=a, group=a)) + 
    geom_line() +
    labs(x="abs(c) / a", y="Acceptance rate", color="a value", title = "a >= 1, c <= 0") +
    theme_minimal() +
    scale_y_continuous(limits = c(0, 1)) +
    scale_color_gradient(low="#72EDF2", high="#736EFE") +
    theme(plot.title = element_text(hjust = 0.5))
  
```

```{r}
# a small, c negative
# Check acceptance rate via simulation
aseq <- seq(1e-2, 1, length.out = 20)
c = seq(0, 100, length.out = 20)

q = 0.5
k1 = 16
k2 = 5

# Create a dataframe
df4 <- map_df(aseq, ~{
  c_values  = - c / (.x)
  data.frame(
    a = .x,
    c = c,
    acceptance_rate = sapply(c_values, get_acceptance_rate, a = .x, q = q, k1 = k1, k2 = k2)
  )
})

# Plot
p4 = ggplot(df4, aes(x=c, y=acceptance_rate, color=a, group=a)) + 
    geom_line() +
    labs(x="a * abs(c)", y="Acceptance rate", color="a value", title = "0 < a < 1, c <= 0") +
    theme_minimal() +
    scale_y_continuous(limits = c(0, 1)) +
    scale_color_gradient(low="#72EDF2", high="#736EFE") +
    theme(plot.title = element_text(hjust = 0.5))
```






